[project]
name = "email-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.6",
    "langchain-chroma>=1.1.0",
    "langchain-ollama>=1.0.1",
    "pandas>=2.3.3",
]
